music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :bands do 
    resources :albums, only: [:new]
  end
  resources :albums, except: [:new]
end

music_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id      :bigint           not null, primary key
#  band_id :integer          not null
#  title   :string           not null
#  year    :integer          not null
#  live    :boolean          default(FALSE), not null
#
class Album < ApplicationRecord
  validates :band_id, :title, :year, :live, presence: true 

  belongs_to :band,
  foreign_key: :band_id,
  class_name: :Band
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id   :bigint           not null, primary key
#  name :string           not null
#
class Band < ApplicationRecord
  validates :name, presence: true 
  
  has_many :albums,
  foreign_key: :band_id,
  class_name: :Band
end

music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#
class User < ApplicationRecord
  validates :email, :session_token, presence: true, uniqueness: true 
  validates :password, length: {minimum:6, allow_nil: true}
  validates :password_digest, presence: true 
  after_initialize :ensure_session_token

  attr_reader :password 

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return user if user && user.is_password?(password)
    nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def password=(password)
    @password = password 
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end
end

music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index 
    @albums = Album.all 
    render :index
  end

  def show
    @album = Album.find_by(id: params[:id])
    render :show 
  end

  def new
    @band = Band.find(params[:band_id])
    @album = Album.new(band_id: params[:band_id])
    render :new
  end

  def create 
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      @band = @album.band
      flash.now[:errors] = @album.errors.full_messages
      render :new 
    end
  end

  def edit 
    @album = Album.find_by(id: params[:id])
    render :edit
  end

  def update
    @album = Album.find_by(id: params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit 
    end
  end

  def destroy
    @album = Album.find_by(id: params[:id])
    @album.destroy 
    redirect_to user_url(current_user)
  end

  def album_params
    params.require(:album).permit(:album_id, :title, :year, :live)
  end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # skip_before_action :verify_authenticity_token
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def require_logged_out
    redirect_to users_url if logged_in?
  end

  def logged_in?
    !!current_user
  end

  def login(user)
    session[:session_token] = user.reset_session_token!
  end
  
  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  # before_action :require_logged_in, only: [:index, :show, :new, :create, :edit, :update. :destroy]

  def index 
    @bands = Band.all 
    render :index 
  end

  def show
    @band = Band.find_by(id: params[:id])
    render :show 
  end

  def new
    @band = Band.new
    render :new
  end

  def create 
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new 
    end
  end

  def edit 
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def update
    @band = Band.find_by(id: params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit 
    end
  end

  def destroy
    @band = Band.find_by(id: params[:id])
    @band.destroy 
    redirect_to user_url(current_user)
  end

  def band_params
    params.require(:band).permit(:name)
  end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 
  before_action :require_logged_out, only: [:new, :create]
  before_action :require_logged_in, only: [:destroy]

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid Credentials"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end 

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController 

  before_action :require_logged_out, only: [:new, :create]
  before_action :require_logged_in, only: [:show]

  def new
    @user = User.new
    render :new 
  end

  def show
    render :show
  end 

  def create
    @user = User.new(user_params)
    if @user.save 
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end



  def user_params
    params.require(:user).permit(:email, :password)
  end
end 

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/views/albums/edit.html.erb
<h1>Edit <%= @album.title %> Album</h1>

<form action="<%= album_url(@album) %>" method="post">
<input type="hidden" name="_method" value="patch">

<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >

<label for="title">Title:</label>
<input type="text" name="album[title]" id="title" value="<%= @album.title %>">

<label for="year">Year:</label>
<input type="text" name="album[year]" id="title" value="<%= @album.year %>">

<label for="album_band">Band</label>
<select name="album[band_id]" id="album_band">
  <% Band.all.each do |band| %>
    <option 
      <%= "selected" if album.band_id == band.id %>
      value="<%= band.id %>">
      <%= band.name %>
    </option>
  <% end %>
</select>



<label for="T">Live</label>
<input type="radio" name="album[live]" id="T" value="true" <%= "checked" if @album.live %>>

<label for="F">Studio</label>
<input type="radio" name="album[live]" id="F" value="false" <%= "checked" if !@album.live %>>


<input type="submit" value="Complete Edit">

</form>

music_app/app/views/albums/index.html.erb
<h1>This Is Album's Index Page</h1>

<ul>
<% @albums.each do |album| %>
<li><%= album.title %></li>
<% end %>
</ul>

music_app/app/views/albums/new.html.erb
<h1>Create A New Album</h1>

<form action="<%= albums_url %>" method="post">

<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >

<label for="title">Title:</label>
<input type="text" name="album[title]" id="title" value="<%= @album.title %>">

<label for="year">Year:</label>
<input type="text" name="album[year]" id="title" value="<%= @album.year %>">

<label for="album_band">Band</label>
<select name="album[band_id]" id="album_band">
  <% Band.all.each do |band| %>
    <option 
      <%= "selected" if album.band_id == band.id %>
      value="<%= band.id %>">
      <%= band.name %>
    </option>
  <% end %>
</select>



<label for="T">Live</label>
<input type="radio" name="album[live]" id="T" value="true" <%= "checked" if @album.live %>>

<label for="F">Studio</label>
<input type="radio" name="album[live]" id="F" value="false" <%= "checked" if !@album.live %>>


<input type="submit" value="Create Album">

</form>

music_app/app/views/albums/show.html.erb
<h1><%= @album.title %>'s Show Page</h1>
<ul>
<%= render @album %>
</ul>

music_app/app/views/bands/edit.html.erb
<h1>Edit <%= @band.name %></h1>

<form action="<%= band_url(@band) %>" method="post">
<input type="hidden" name="_method" value="patch">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >

<label for="name"></label>
<input type="text" name="band[name]" id="name" value="<%= @band.name %>">


<input type="submit" value="Create Band">

</form>

music_app/app/views/bands/index.html.erb
<h1>This Is Bands Index Page</h1>

<ul>
<% @bands.each do |band| %>
<li><%= band.name %></li>
<% end %>
</ul>

music_app/app/views/bands/new.html.erb
<h1>Create A New Band</h1>

<form action="<%= bands_url %>" method="post">

<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >

<label for="name"></label>
<input type="text" name="band[name]" id="name">


<input type="submit" value="Create Band">

</form>

music_app/app/views/bands/show.html.erb
<h1><%= @band.name %>'s Show Page</h1>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<header>Music APP</header>

<%# <style>
  div {
    display: flex;
    justify-content: center;
  }
</style> %>




<% if logged_in? %>

<form action="<%= session_url %>" method="post" >
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
<input type="hidden" name="_method" value="delete">
<input type="submit" value="LOG OUT!">
</form>

<% else %>
<div>
  <a href="<%= new_user_url %>">Sign up!</a>
  <a href="<%= new_session_url %>">Log in!</a>
  </div>
<% end %>
  <body>
    <%= yield %>
  </body>

  <% if flash[:errors] %>
    <ul>
      <% flash[:errors].each do |error| %>
      <li><%= error %></li>
      <% end %>
    </ul>

  <% end %>
</html>

music_app/app/views/users/new.html.erb
<h1>Create a User</h1>


<form action="<%= users_url %>" method="post">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
<label for="email">Email:</label>
<input type="text" name="user[email]" id="email" value="<%= @user.email %>">

<label for="password">Password:</label>
<input type="password" name="user[password]" id="password" value="">

<input type="submit" value="Create User!">

</form>

music_app/app/views/users/show.html.erb
<h1>This is your show page</h1>

<p>
  Email: <%= current_user.email %>
</p>